name: TonRunner
favicon: null
layout_spectrum: 0.37585
typography_spectrum: 0.35195
title: 'Swim Bike Run - Tonbridge, Kent, UK'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
