name: TonRunner
favicon: null
layout_spectrum: 0.80754
typography_spectrum: 0.40109
title: 'Swim | Cycle | Run'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252839'
    - '#6b6b6d'
    - '#f2f2f4'
    - '#434554'
    - '#466d00'
  brandStrength: 0.159909
  lightness: 0.656531
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
