analytics:
  google: UA-71200215-1
color:
  brandColors:
    - '#252839'
    - '#6b6b6d'
    - '#f2f2f4'
    - '#434554'
    - '#466d00'
  brandStrength: 0.159909
  lightness: 0.656531
  rhythmicContrast: 0.25
  saturation: 1
cta: {}
layout_spectrum: 0.70025
name: TonRunner
opengraph: {}
purpose: []
typography_spectrum: 0.40109
