analytics:
  google: UA-71200215-1
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.3125
  lightness: 0.625
  rhythmicContrast: 0.75
  saturation: 0.5625
cta: {}
layout_spectrum: 0.457207
name: TonRunner
opengraph: {}
purpose: []
typography_spectrum: 0.31619
