name: TonRunner
favicon: null
layout_spectrum: 0.13849
typography_spectrum: 0.37692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.384009
  lightness: 0.546171
  saturation: 0.420045
  rhythmicContrast: 1
purpose: []
