name: TonRunner
favicon: null
layout_spectrum: 0.66477
typography_spectrum: 0.17221
title: 'Swim Bike Run - Tonbridge, Kent, UK'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
purpose: []
