typography_spectrum: 0.40109
color:
  brandColors:
    - '#252839'
    - '#6b6b6d'
    - '#f2f2f4'
    - '#434554'
    - '#466d00'
  brandStrength: 0.159909
  lightness: 0.656531
  saturation: 1
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48396
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
author:
  name: Anthony Lester
  email: alester229@gmail.com
  url: tonrunner.uk
name: TonRunner
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 9992db98-edef-4ff6-b121-dd52015e3fd2
    name: 2016 Race Schedule
    type: content
favicon: null
title: Swim | Cycle | Run
purpose: []
