name: TonRunner
favicon: null
layout_spectrum: 0.37669
typography_spectrum: 0.23509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.338963
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
