name: TonRunner
favicon: null
layout_spectrum: 0.43754
typography_spectrum: 0.30316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272822'
    - '#584729'
    - '#423b2b'
    - '#827354'
    - '#838254'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
