layout_spectrum: 0.16021267953328788
typography_spectrum: 0.5630923581775278
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.05942410114221275
  lightness: 0.4730572688858956
  saturation: 0.16155924182385206
  rhythmicContrast: 0.7828870876692235
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
author:
  name: Anthony Lester
  email: alester229@gmail.com
  url: tonrunner.uk
name: TonRunner
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 9992db98-edef-4ff6-b121-dd52015e3fd2
    name: 2016 Race Schedule
    type: content
  - url: 'https://twitter.com/alester229'
    name: Twitter
    type: external
favicon: null
title: Swim | Cycle | Run
purpose: []
