name: TonRunner
favicon: null
layout_spectrum: 0.44563
typography_spectrum: 0.40109
title: 'Swim | Cycle | Run'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71200215-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252839'
    - '#6b6b6d'
    - '#f2f2f4'
    - '#434554'
    - '#ff6600'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
